site_name: RestMachine ORM
site_description: ActiveRecord-style ORM/ODM for RestMachine
docs_dir: docs

nav:
  - ORM:
    - Overview: index.md
    - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Basic Usage: getting-started/usage.md
    - Backends:
      - In-Memory: backends/inmemory.md
      - DynamoDB: backends/dynamodb.md
    - Testing:
      - Multi-Backend Testing: testing/multi-backend.md
    - API Reference:
      - Models: api/models.md
      - Backends: api/backends.md
      - Query Interface: api/query.md
