[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "restmachine-orm"
version = "0.1.0"
description = "ActiveRecord-style ORM/ODM for RestMachine with support for OpenSearch and composite backends. DynamoDB support is available in restmachine-orm-dynamodb."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "RestMachine Contributors"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "pydantic>=2.0.0",
    "typing-extensions>=4.0.0",
]

[project.optional-dependencies]
# DynamoDB support has moved to restmachine-orm-dynamodb package
dynamodb = [
    "restmachine-orm-dynamodb>=0.1.0",
]
opensearch = [
    "opensearch-py>=2.0.0",
]
# Testing framework is in restmachine-orm-testing package (local)
# For local development, install with: pip install -e ./packages/restmachine-orm-testing
testing = []
all = [
    "restmachine-orm-dynamodb>=0.1.0",
    "opensearch-py>=2.0.0",
]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/anthropics/restmachine-python"
Documentation = "https://restmachine.readthedocs.io/"
Repository = "https://github.com/anthropics/restmachine-python"

[tool.hatch.build.targets.wheel]
packages = ["src/restmachine_orm"]
artifacts = [
    "src/restmachine_orm/py.typed",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --strict-markers"
markers = [
    "unit: Unit tests",
    "integration: Integration tests requiring external services",
    "opensearch: OpenSearch-specific tests",
]

[tool.coverage.run]
source = ["src/restmachine_orm"]
omit = ["*/tests/*", "*/test_*.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]
