site_name: RestMachine AWS
docs_dir: docs

nav:
  - Overview: index.md
  - Guides:
    - Lambda Deployment: guides/lambda-deployment.md
    - Lambda Extensions: guides/lambda-extensions.md
  - API Reference:
    - Adapter: api/adapter.md
    - Extension: api/extension.md
