[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "restmachine-aws"
dynamic = ["version"]
description = "AWS Lambda adapter for RestMachine framework"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Ryan Festag", email = "rfestag@gmail.com"}
]
keywords = ["rest", "api", "aws", "lambda", "api-gateway", "serverless"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "restmachine>=0.1.0",
]

[project.optional-dependencies]
test = [
    "pytest>=6.0",
    "pytest-cov",
]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "ruff",
    "mypy",
    "radon>=6.0.0",
]

[project.urls]
Homepage = "https://github.com/rfestag/restmachine-python"
Repository = "https://github.com/rfestag/restmachine-python"
"Bug Reports" = "https://github.com/rfestag/restmachine-python/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["restmachine_aws*"]
exclude = ["tests*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"

[tool.setuptools_scm]
root = "../.."
tag_regex = "^restmachine-aws-(?P<version>[vV]?\\d+(?:\\.\\d+)*(?:[a-zA-Z-]+(?:\\.\\d+)?)?)$"
version_file = "src/restmachine_aws/_version.py"
