[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "restmachine-web"
version = "0.1.0"
description = "Static file serving extension for RestMachine framework"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Ryan Festag", email = "rfestag@gmail.com"}
]
keywords = ["rest", "api", "static", "files", "web", "http"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "restmachine>=0.1.0",
]

[project.optional-dependencies]
s3 = [
    "boto3>=1.26.0",
]
test = [
    "pytest>=6.0",
    "pytest-cov",
]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "ruff",
    "mypy",
]

[project.urls]
Homepage = "https://github.com/rfestag/restmachine-python"
Repository = "https://github.com/rfestag/restmachine-python"
"Bug Reports" = "https://github.com/rfestag/restmachine-python/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["restmachine_web*"]
exclude = ["tests*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
