[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "restmachine-uvicorn"
version = "0.1.0"
description = "Uvicorn server adapter for RestMachine framework"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Ryan Festag", email = "rfestag@gmail.com"}
]
keywords = ["rest", "api", "uvicorn", "asgi", "http"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "restmachine>=0.1.0",
    "uvicorn>=0.20.0",
]

[project.optional-dependencies]
test = [
    "pytest>=6.0",
    "pytest-cov",
    "requests",
]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "requests",
    "ruff",
    "mypy",
]

[project.urls]
Homepage = "https://github.com/rfestag/restmachine-python"
Repository = "https://github.com/rfestag/restmachine-python"
"Bug Reports" = "https://github.com/rfestag/restmachine-python/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["restmachine_uvicorn*"]
exclude = ["tests*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
markers = [
    "driver_uvicorn_http1: Tests using Uvicorn HTTP/1.1 driver",
    "performance: Performance benchmark tests",
]
filterwarnings = [
    "ignore:websockets.legacy is deprecated.*:DeprecationWarning",
    "ignore:websockets.server.WebSocketServerProtocol is deprecated.*:DeprecationWarning",
]
