name: Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Monday at 9am UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run security scans
      run: tox -e security

    - name: Verify SARIF file exists
      if: always()
      run: |
        if [ -f bandit-report.sarif ]; then
          echo "✅ SARIF file generated successfully"
          cat bandit-report.sarif | python3 -m json.tool > /dev/null && echo "✅ SARIF file is valid JSON"
        else
          echo "❌ SARIF file not found"
          exit 1
        fi

    - name: Upload Bandit SARIF results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: bandit-report.sarif
        category: bandit

    - name: Upload pip-audit markdown report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pip-audit-report
        path: pip-audit-report.md

    - name: Upload security reports as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.sarif
          pip-audit-report.md
